- name: Test
  hosts: all
  gather_facts: false
  strategy: ansible.builtin.linear

  vars:
    test: ici
    pwd: "{{ lookup('env','PWD') }}"

  tasks:
    - name: Test1
      ansible.builtin.debug:
        var: groups

    - name: Test2
      ansible.builtin.lineinfile:
        path: "{{ pwd }}/test.txt"
        line: "{{ ansible_play_hosts }}: {{ ansible_play_hosts | join | shuffle | join }}"
        create: true
        mode: "0644"

    - name: Test3
      ansible.builtin.debug:
        msg: "{{ pwd }}"
      delegate_to: localhost
      run_once: true
